services:
  api:
    image: platzi-store-api
    build: .
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    depends_on:
      - database
    command: ["npm", "run", "dev"]
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - platzi_store_db:/var/lib/postgresql/data
volumes:
  platzi_store_db: {}

